import{a as g,S as b,i}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const L="50842671-b6a5d06ede8a88fc17f0ce411",w="https://pixabay.com/api/",v=15;async function S(e,n=1){const o={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:n};return(await g.get(w,{params:o})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".btn-more"),q=new b(".gallery a");function P(e){const n=e.map(o=>`
        <li class="gallery-item">
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o.likes}</p>
            <p><b>Views:</b> ${o.views}</p>
            <p><b>Comments:</b> ${o.comments}</p>
            <p><b>Downloads:</b> ${o.downloads}</p>
          </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",n),q.refresh()}function R(){p.innerHTML=""}function B(){m.classList.add("show")}function f(){m.classList.remove("show")}function E(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const M=document.querySelector(".form"),$=document.querySelector(".input"),O=document.querySelector(".btn-more");let l="",s=1,u=0;M.addEventListener("submit",async e=>{if(e.preventDefault(),l=$.value.trim(),s=1,R(),d(),!l){i.warning({title:"Oops!",message:"Please enter a search term.",position:"topRight"});return}await y()});O.addEventListener("click",async()=>{s+=1,await y()});async function y(){B();try{const e=await S(l,s);if(f(),u=e.totalHits,e.hits.length===0&&s===1){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}P(e.hits),x(e.hits.length),s>1&&A(),s*15>=u&&(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){f(),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}}function x(e){e<15||s*15>=u?d():E()}function A(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
